#!/bin/sh

cd / || exit 1
[ -f .meta ] || exit 0

while read -r mode owner group path; do
	[ -h "$path" ] && continue
	[ -e "$path" ] || continue
	chown "$owner:$group" "$path"
	chmod "$mode" "$path"
done < .meta

if [ -s .pkg ] && ! pkg_info -mz | cmp -s - .pkg; then
	pkg_add -I -x -l .pkg
fi
