permit persist :wheel
permit nopass keepenv root
permit nopass keepenv xlzs0 as _pbuild
permit nopass keepenv xlzs0 as _pfetch
permit nopass xlzs0 as cliamp cmd /usr/local/bin/cliamp-bin
permit nopass xlzs0 as discordo cmd /usr/local/bin/discordo-bin
#permit nopass xlzs0 cmd btrace
#permit nopass xlzs0 cmd vmctl
